Vagrant.configure("2") do |config|

	config.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "1024"]
	end

	config.vm.box = "avenuefactory/lamp"

	#config.vm.network :private_network, ip: "192.168.10.10"

	config.vm.network :forwarded_port,
		host: 4000,
		guest: 80

	config.vm.synced_folder "dist", "/var/www/html", owner: "www-data", group: "www-data"
	config.vm.synced_folder "database", "/var/www/database"


	config.trigger.before [:destroy, :halt, :suspend] do
		backup = ask( "Do you want to backup the database? (y/n)" )
		if backup == 'y'
			info "Backing up WordPress database..."
			run "vagrant ssh -c 'bash /var/www/database/backup_db.sh'"
		end
	end

	config.trigger.after [:up] do
		import = ask( "Do you want to import the database? (y/n)" )
		if import == 'y'
			info "Importing WordPress database from backup..."
			run "vagrant ssh -c 'bash /var/www/database/import_db.sh'"
		end
	end

end
